name: learn-github-actions
on:
    push:
        branches:
            - main
jobs:
  python-hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          # 현재 가장 최신 안정화 버전인 3.13을 사용합니다.
          # 특정 패키지 호환성이 중요하다면 3.12를 사용해도 좋습니다.
          python-version: "3.13"

      - name: Display Python version
        run: python --version

      - name: Execute Python script
        run: python -c "print('hello world from Python 3.13!')"

